source 'https://rubygems.org'

gem 'sinatra'
gem 'cucumber'
gem 'cucumber-sinatra'
gem 'rspec'
gem 'shotgun'
gem 'capybara'
gem 'launchy'
gem 'bundler'
gem 'nokogiri'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'